cardio_causa:
    resource: "@CardioBundle/Resources/config/routing/causadescompensante.yml"
    prefix:   /admin/causa
cardio_estado_evolutivo:
    resource: "@CardioBundle/Resources/config/routing/estadoevolutivo.yml"
    prefix:   /admin/estado-evolutivo
cardio_factor_riesgo:
    resource: "@CardioBundle/Resources/config/routing/factorriesgo.yml"
    prefix:   /admin/factor-riesgo
cardio_ficha:
    resource: "@CardioBundle/Resources/config/routing/ficha.yml"
    prefix:   /ficha
cardio_medicacion:
    resource: "@CardioBundle/Resources/config/routing/medicacion.yml"
    prefix:   /admin/medicacion
cardio_paciente:
    resource: "@CardioBundle/Resources/config/routing/paciente.yml"
    prefix:   /paciente
cardio_rx-torax:
    resource: "@CardioBundle/Resources/config/routing/rxtorax.yml"
    prefix:   /admin/rx-torax
cardio_user:
    resource: "@CardioBundle/Resources/config/routing/usuario.yml"
    prefix:   /admin/user

cardio_homepage:
    path:     /
    defaults: { _controller: CardioBundle:Paciente:index }

login:
    path:     /login
    defaults: { _controller: CardioBundle:Usuario:login }

login_check:
    path:     /login_check
    defaults: { _controller: CardioBundle:Usuario:loginCheck }

logout:
    path: /logout
    defaults: { _controller: CardioBundle:Usuario:logout }
