cardio_causa:
    resource: "@CardioBundle/Resources/config/routing/causadescompensante.yml"
    prefix:   /causa
cardio_causa:
    resource: "@CardioBundle/Resources/config/routing/estadoevolutivo.yml"
    prefix:   /estado-evolutivo
cardio_causa:
    resource: "@CardioBundle/Resources/config/routing/factorriesgo.yml"
    prefix:   /factor-riesgo
cardio_causa:
    resource: "@CardioBundle/Resources/config/routing/ficha.yml"
    prefix:   /ficha
cardio_causa:
    resource: "@CardioBundle/Resources/config/routing/medicacion.yml"
    prefix:   /medicacion
cardio_causa:
    resource: "@CardioBundle/Resources/config/routing/paciente.yml"
    prefix:   /paciente
    
cardio_homepage:
    path:     /
    defaults: { _controller: CardioBundle:Default:index }
