factor-riesgo_index:
    path:     /
    defaults: { _controller: "CardioBundle:FactorRiesgo:index" }
    methods:  GET

factor-riesgo_show:
    path:     /{id}/show
    defaults: { _controller: "CardioBundle:FactorRiesgo:show" }
    methods:  GET

factor-riesgo_new:
    path:     /new
    defaults: { _controller: "CardioBundle:FactorRiesgo:new" }
    methods:  [GET, POST]

factor-riesgo_edit:
    path:     /{id}/edit
    defaults: { _controller: "CardioBundle:FactorRiesgo:edit" }
    methods:  [GET, POST]

factor-riesgo_delete:
    path:     /{id}/delete
    defaults: { _controller: "CardioBundle:FactorRiesgo:delete" }
    methods:  DELETE
