ficha_index:
    path:     /
    defaults: { _controller: "CardioBundle:Ficha:index" }
    methods:  GET

ficha_show:
    path:     /{id}/show
    defaults: { _controller: "CardioBundle:Ficha:show" }
    methods:  GET

ficha_new:
    path:     /new
    defaults: { _controller: "CardioBundle:Ficha:new" }
    methods:  [GET, POST]

ficha_edit:
    path:     /{id}/edit
    defaults: { _controller: "CardioBundle:Ficha:edit" }
    methods:  [GET, POST]

ficha_delete:
    path:     /{id}/delete
    defaults: { _controller: "CardioBundle:Ficha:delete" }
    methods:  DELETE
