historia-clinica_index:
    path:     /
    defaults: { _controller: "CardioBundle:HistoriaClinica:index" }
    methods:  GET

historia-clinica_show:
    path:     /{id}/show
    defaults: { _controller: "CardioBundle:HistoriaClinica:show" }
    methods:  GET

historia-clinica_new:
    path:     /new
    defaults: { _controller: "CardioBundle:HistoriaClinica:new" }
    methods:  [GET, POST]

historia-clinica_edit:
    path:     /{id}/edit
    defaults: { _controller: "CardioBundle:HistoriaClinica:edit" }
    methods:  [GET, POST]

historia-clinica_delete:
    path:     /{id}/delete
    defaults: { _controller: "CardioBundle:HistoriaClinica:delete" }
    methods:  DELETE
