rx-torax_index:
    path:     /
    defaults: { _controller: "CardioBundle:RxTorax:index" }
    methods:  GET

rx-torax_show:
    path:     /{id}/show
    defaults: { _controller: "CardioBundle:RxTorax:show" }
    methods:  GET

rx-torax_new:
    path:     /new
    defaults: { _controller: "CardioBundle:RxTorax:new" }
    methods:  [GET, POST]

rx-torax_edit:
    path:     /{id}/edit
    defaults: { _controller: "CardioBundle:RxTorax:edit" }
    methods:  [GET, POST]

rx-torax_delete:
    path:     /{id}/delete
    defaults: { _controller: "CardioBundle:RxTorax:delete" }
    methods:  DELETE
