user_index:
    path:     /
    defaults: { _controller: "CardioBundle:Usuario:index" }
    methods:  GET

user_show:
    path:     /{id}/show
    defaults: { _controller: "CardioBundle:Usuario:show" }
    methods:  GET

user_new:
    path:     /new
    defaults: { _controller: "CardioBundle:Usuario:new" }
    methods:  [GET, POST]

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "CardioBundle:Usuario:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "CardioBundle:Usuario:delete" }
    methods:  DELETE
